<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ThreshInfra</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi" Version="3.100.0" />
    <PackageReference Include="Pulumi.VSphere" Version="4.12.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
  </ItemGroup>

</Project>
